name: umi-pipeline-nf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8
  - medaka>2.0.0
  - minimap2=2.24
  - samtools=1.15.1
  - seqtk=1.3
  - lofreq=2.1.5
  - freebayes=1.3.2
  - vcflib=1.0.0
  - bedtools=2.30.0
  - vsearch=2.21.2
  - openjdk=11.0.9
  - unzip=6.0
  - pip=22.2.2
