name: umi-pipeline-nf
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python~=3.8
  - pip=22.2.2
  - bedtools=2.30.0
  - samtools=1.15.1
  - seqtk=1.3
  - minimap2=2.24
  - freebayes=1.3.2
  - lofreq=2.1.5
  - medaka=2.0.1
  - vcflib=1.0.0_rc2
  - vsearch=2.21.2
  - pyabpoa=1.5.3
  - pyspoa=0.2.1
  - edlib=1.3.9
  - openjdk=11.0.9.1
  - unzip=6.0
  - wget=1.21.4
  - pysam=0.22.1
  - numpy=1.24.4
  - pandas=1.5.0
  - networkx=3.1
  - matplotlib=3.7.2
  # Medaka subtools
  - bcftools=1.21
  - ont-fast5-api=4.1.3
  - h5py~=3.10.0
  - cffi=1.17.0
  - bzip2=1.0.8
  - pytorch=2.3.1
  - tqdm=4.67.1
  - requests=2.32.3
  - packaging=25.0
  - intervaltree=3.1.0
  - pip:
      - catfishq==1.4.0
